### ISSUE TITLE
Bad data directory

### ISSUE THREAD

**Issue by jdemeyer** [conda-forge/pari-feedstock#4]
Running `print(default(datadir))` inside `gp` gives a data directory
```
/feedstock_root/build_artefacts/pari_1493573901811/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/pari
```
For some reason, this path is not fixed. It is stored as 0-terminated string in `lib/libpari-gmp.so.2.9.2`.

I am running into this issue because of https://github.com/defeo/cypari2/issues/18

This is using the conda-forge package `pari-2.9.2-pl5`

**Comment by isuruf** [comment]
I don't get this issue. Can you try updating `conda`?

**Comment by jdemeyer** [comment]
> Can you try updating conda?

Absolutely not since this is inside the ReadTheDocs server.

**Comment by jdemeyer** [comment]
I managed to work around this problem. If you're sure that it's a Conda problem and not a problem with this package, feel free to close it.

**Comment by isuruf** [comment]
This is what I have in the `info/has_prefix` file of the conda package tarball,
```
/feedstock_root/build_artefacts/pari_1493573901811/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho binary lib/libpari-gmp.so.2.9.2
/opt/anaconda1anaconda2anaconda3 text bin/gphelp
/opt/anaconda1anaconda2anaconda3 text bin/tex2mail
/opt/anaconda1anaconda2anaconda3 text include/pari/paricfg.h
/opt/anaconda1anaconda2anaconda3 text lib/pari/pari.cfg
/opt/anaconda1anaconda2anaconda3 text share/pari/doc/paricfg.tex
/opt/anaconda1anaconda2anaconda3 text share/pari/examples/Makefile
```
So, the above path should be replaced by conda. I'm almost 100% sure this is an issue with conda.
